### ISSUE TITLE
Should we kick rebounding messages for now?

### ISSUE THREAD

**Issue by DominikKoller** [DominikKoller/pxt-Parties#2]
We'll have a working prototype quicker if we stop caring about rebounding messages. Maybe keep some space in the messages for the message ID still so we don't have to redesign that later on.

**Comment by DominikKoller** [comment]
It's already implemented for the heartbeat though, let's keep that in there. Then we will have members in the list that we can't send messages to if they're two hops away but I guess that's fine.

**Comment by sarthakjainMagd** [comment]
Ok for now let's do that. If everyone can't be reached within one hop, then the PartyTable for each device will slightly different, so the overall network will be a cluster of smaller clusters rather than one big cluster. With that said, as long as there exists a path (with greater than equal  or to one edge) between each device in the party, then the higher level "duck game should still function". However, to have  consistency between the contents of the party table and what's actually possible to transmit, the heartbeat messages should not be rebounded...

**Comment by DominikKoller** [comment]
Yep we can simply set the Max Hop Value to 1 then also heartbeat messages will never be rebounded.
