### ISSUE TITLE
Integer Overflow on messageId

### ISSUE THREAD

**Issue by DominikKoller** [DominikKoller/pxt-Parties#7]
We need to deal with integer overflow on the messageId. Right now, once the messageId overflows, none of the sent messages will be received any more.

How to deal with this:
don't simply use greater than comparison, but do something like

uint8_t diff = prefix.messageId - sender->messageId;
if(diff != 0 && diff < 128) {
...
}

Do not close this issue before extensively testing this (including confirming the original issue).

**Comment by AlexMorson** [comment]
Commit f5eccf93003639e04608448f6127380b2e25c2dd implements this change.

**Testing the behaviour before the change:**
I wrote a simple program that receives a number, adds 1 to it and then sends it out to a random micro:bit. I also temporarily added some debug output statements to monitor the message ids.
The numbers would increase, being sent back and forth, until around 400, where they would stop. Looking at the message ids, it was clear that this was the point at which they were reaching 255 and then wrapping back down to 0, meaning that the other micro:bit would ignore the new messages. Then, because no valid messages were being received, after 7 seconds each micro:bit was cleared from the others' routing table and on receiving the next heartbeat were added back in with correct `lastMessageId`s.

**After the change:**
With the same setup, the micro:bits were able to count to over 4000 without failing (at which point I stopped the test).

**Unchanged behaviour:**
Resetting one of the micro:bits can cause the others to ignore the first few messages it sends - because they may already have an entry in their routing table with a `lastMessageId` low enough to not wrap around upon receiving a message with id 0. But this is guaranteed to fix itself within 7 seconds due to the old entry timing out.
